// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: pb/serf_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SerfClient is the client API for Serf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SerfClient interface {
	Hello(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
}

type serfClient struct {
	cc grpc.ClientConnInterface
}

func NewSerfClient(cc grpc.ClientConnInterface) SerfClient {
	return &serfClient{cc}
}

func (c *serfClient) Hello(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, "/pb.Serf/hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SerfServer is the server API for Serf service.
// All implementations must embed UnimplementedSerfServer
// for forward compatibility
type SerfServer interface {
	Hello(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error)
	mustEmbedUnimplementedSerfServer()
}

// UnimplementedSerfServer must be embedded to have forward compatible implementations.
type UnimplementedSerfServer struct {
}

func (UnimplementedSerfServer) Hello(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedSerfServer) mustEmbedUnimplementedSerfServer() {}

// UnsafeSerfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SerfServer will
// result in compilation errors.
type UnsafeSerfServer interface {
	mustEmbedUnimplementedSerfServer()
}

func RegisterSerfServer(s grpc.ServiceRegistrar, srv SerfServer) {
	s.RegisterService(&Serf_ServiceDesc, srv)
}

func _Serf_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SerfServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Serf/hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SerfServer).Hello(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// Serf_ServiceDesc is the grpc.ServiceDesc for Serf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Serf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Serf",
	HandlerType: (*SerfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "hello",
			Handler:    _Serf_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/serf_service.proto",
}
